// Placeholder data for local preview only. Once SUPABASE_URL and
// SUPABASE_SERVICE_ROLE_KEY are set, build.js pulls real rows instead.
const products = [
  {
    id: 'sample-iphone-17-pro',
    slug: 'iphone-17-pro',
    name: 'iPhone 17 Pro',
    category: 'iPhone',
    price: '£1,099',
    chip: 'A19 Pro',
    image_urls: [], video_url: null,
    refresh_history: ['2023-09-22', '2024-09-20', '2025-09-19'],
    rumor_note: 'Next model expected around September 2026, no major design change rumoured.',
    featured: true,
    waiting_count: 128,
    discontinued: false,
  },
  {
    id: 'sample-mac-mini',
    slug: 'mac-mini',
    name: 'Mac mini',
    category: 'Mac',
    price: '£599',
    chip: 'M5',
    image_urls: [], video_url: null,
    refresh_history: ['2023-10-30', '2026-08-15'],
    rumor_note: 'Just refreshed, next update not expected for a while.',
    featured: false,
    waiting_count: 12,
    discontinued: false,
  },
  {
    id: 'sample-ipad-air',
    slug: 'ipad-air',
    name: 'iPad Air',
    category: 'iPad',
    price: '£749',
    chip: 'M4',
    image_urls: [], video_url: null,
    refresh_history: ['2024-05-15', '2026-03-12'],
    rumor_note: 'No new model expected before spring 2027.',
    featured: false,
    waiting_count: 34,
    discontinued: false,
  },
  {
    id: 'sample-macbook-air',
    slug: 'macbook-air',
    name: 'MacBook Air',
    category: 'Mac',
    price: '£1,099',
    chip: 'M3',
    image_urls: [], video_url: null,
    refresh_history: ['2023-06-05', '2024-03-04', '2025-03-04'],
    rumor_note: 'Refreshed 13 and 15-inch models rumoured for early 2027 with the M6 chip.',
    featured: false,
    waiting_count: 261,
    discontinued: false,
    previous_model: 'macbook-12-inch',
    days_basis: 'launch',
  },
  {
    id: 'sample-watch-ultra',
    slug: 'apple-watch-ultra',
    name: 'Apple Watch Ultra',
    category: 'Apple Watch',
    price: '£799',
    chip: 'S10',
    image_urls: [], video_url: null,
    refresh_history: ['2023-09-22', '2024-09-20', '2025-09-19'],
    rumor_note: 'Expected around September 2026, based on the yearly pattern.',
    featured: false,
    waiting_count: 87,
    discontinued: false,
  },
  {
    id: 'sample-airpods-max',
    slug: 'airpods-max',
    name: 'AirPods Max',
    category: 'AirPods',
    price: '£549',
    chip: null,
    image_urls: [], video_url: null,
    refresh_history: ['2020-12-15', '2024-12-10'],
    rumor_note: 'No refresh rumoured yet.',
    featured: false,
    waiting_count: 45,
    discontinued: false,
  },
  {
    id: 'sample-ipod-touch',
    slug: 'ipod-touch',
    name: 'iPod touch',
    category: 'Other',
    price: null,
    chip: 'A10 Fusion',
    image_urls: [], video_url: null,
    refresh_history: ['2019-05-28'],
    rumor_note: null,
    featured: false,
    waiting_count: 6,
    discontinued: true,
    discontinued_date: '2022-05-10',
    replaced_by: 'iphone-17-pro',
    discontinued_reason: 'The last iPod. The iPhone had long since made a phone-less iPod redundant.',
  },
  {
    id: 'sample-homepod-original',
    slug: 'homepod-original',
    name: 'HomePod (1st generation)',
    category: 'Other',
    price: null,
    chip: 'A8',
    image_urls: [], video_url: null,
    refresh_history: ['2018-02-09'],
    rumor_note: null,
    featured: false,
    waiting_count: 3,
    discontinued: true,
    discontinued_date: '2021-03-12',
    replaced_by: null,
    discontinued_reason: 'Outsold by the cheaper HomePod mini. A second-generation HomePod arrived two years later.',
  },
  {
    id: 'sample-macbook-12inch',
    slug: 'macbook-12-inch',
    name: 'MacBook (12-inch)',
    category: 'Mac',
    price: '1299',
    chip: 'Intel Core m3/i5/i7',
    image_urls: [], video_url: null,
    refresh_history: ['2015', '2016-04', '2017-06-05'],
    rumor_note: null,
    featured: false,
    waiting_count: 2,
    discontinued: true,
    discontinued_date: '2019-07-09',
    replaced_by: 'macbook-air',
    previous_model: null,
    days_basis: 'refresh',
    discontinued_reason: 'Squeezed out by the redesigned MacBook Air, which was thinner, faster and cheaper.',
  },
  // AirPods family: three product lines, each with its own generations.
  {
    id: 'sample-airpods', slug: 'airpods', name: 'AirPods', category: 'AirPods', price: '$129',
    image_urls: [], video_url: null,
    refresh_history: ['2016-12-13', '2019-03-20', '2021-10-26', '2024-09-20'],
    generation_details: {
      '2016-12-13': { name: 'AirPods (1st generation)', announced: '2016-09-07' },
      '2024-09-20': { name: 'AirPods 4', announced: '2024-09-09' },
    },
    original_launch_date: '2016-12-13',
    featured: false, waiting_count: 40, discontinued: false,
  },
  {
    id: 'sample-airpods-pro', slug: 'airpods-pro', name: 'AirPods Pro', category: 'AirPods', price: '$249',
    image_urls: [], video_url: null,
    refresh_history: ['2019-10-30', '2022-09-23', '2025-09-19', '2026-10-23'],
    generation_details: {},
    timeline_name: 'AirPods Pro',
    apple_url: 'https://www.apple.com/airpods-pro/',
    specs_url: 'https://support.apple.com/en-gb/111851',
    press_release_url: 'https://www.apple.com/newsroom/2025/09/airpods-pro-3/',
    external_link: 'https://en.wikipedia.org/wiki/AirPods_Pro',
    featured: false, waiting_count: 22, discontinued: false,
  },
];

module.exports = { products };
